[
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "\n```\n.............................E\n======================================================================\nERROR: test_recentArticle (__main__.testXenagos)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/testing.py\", line 459, in test_recentArticle\n    days = (datetime.datetime.today() -  datetime.datetime.strptime(date.decode(), '%b %d, %Y')).days\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 510, in _strptime_datetime\n    tt, fraction = _strptime(data_string, format)\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 346, in _strptime\n    data_string[found.end():])\nValueError: unconverted data remains: \"\n\n----------------------------------------------------------------------\nRan 30 tests in 5.177s\n\nFAILED (errors=1)\n\n```",
        "ts": "1570003494.056400",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-02 08:12:01,853 INFO cards.py took 0:11:53.009174\n```",
        "ts": "1570003909.056500",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-02 08:15:08,644 INFO New Trending 2019-10-02\n{\"name\": \"Fabled Passage\", \"s\": [0, 22, 21, 12, 34, 42, 33], \"z\": 1.2267730969396924}\n{\"name\": \"Siege-Gang Commander\", \"s\": [0, 12, 8, 12, 18, 21, 20], \"z\": 1.21901426693758}\n{\"name\": \"Stitcher's Supplier\", \"s\": [0, 11, 9, 7, 18, 22, 20], \"z\": 1.2170516357027072}\n{\"name\": \"Wishclaw Talisman\", \"s\": [0, 4, 3, 5, 10, 14, 12], \"z\": 1.2145940834130933}\n{\"name\": \"Extraplanar Lens\", \"s\": [0, 12, 10, 11, 20, 19, 20], \"z\": 1.2114883225490194}\n{\"name\": \"Mystic Sanctuary\", \"s\": [0, 5, 7, 8, 14, 12, 14], \"z\": 1.1969353597749286}\n{\"name\": \"Spinerock Knoll\", \"s\": [0, 11, 9, 10, 17, 18, 18], \"z\": 1.1886876651634484}\n{\"name\": \"Serum Visions\", \"s\": [0, 19, 16, 17, 32, 26, 26], \"z\": 1.1828833699228647}\n{\"name\": \"Wonder\", \"s\": [0, 6, 7, 7, 17, 19, 11], \"z\": 1.1725644600766965}\n{\"name\": \"Sylvan Caryatid\", \"s\": [0, 7, 6, 9, 18, 14, 12], \"z\": 1.1716452766064636}\n2019-10-02 08:15:08,670 INFO daily.py took 0:15:00.058987\n```",
        "ts": "1570004096.056600",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-02 08:15:14,932 INFO backup.py took 0:15:06.347878\n```",
        "ts": "1570004102.056700",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-02 08:39:07,985 INFO archidekt.py took 0:22:40.401015\n```",
        "ts": "1570005536.056800",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-02 09:06:38,795 INFO deckstats.py took 0:25:27.376630\n```",
        "ts": "1570007186.056900",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-02 09:56:03,971 INFO mtggoldfish.py took 0:29:06.466991\n```",
        "ts": "1570010152.057000",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "\n```\n.............................E\n======================================================================\nERROR: test_recentArticle (__main__.testXenagos)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/testing.py\", line 459, in test_recentArticle\n    days = (datetime.datetime.today() -  datetime.datetime.strptime(date.decode(), '%b %d, %Y')).days\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 510, in _strptime_datetime\n    tt, fraction = _strptime(data_string, format)\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 346, in _strptime\n    data_string[found.end():])\nValueError: unconverted data remains: \"\n\n----------------------------------------------------------------------\nRan 30 tests in 6.043s\n\nFAILED (errors=1)\n\n```",
        "ts": "1570010695.057100",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-02 10:44:27,547 INFO update_deckswithprices.py took 0:31:27.638438\nNew deck count from past 2 days: \n- MTGGoldfish: 384\n- Archidekt: 418\n- deckstats: 314\n- Other: 0\n```",
        "ts": "1570013055.057200",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-02 10:55:28,512 INFO cache_get_cards took 0:10:54.865276\n```",
        "ts": "1570013716.057300",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "Nightly started, onlydecks=False, skipdecks=False",
        "ts": "1570013722.057400",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "\n```\n.............................E\n======================================================================\nERROR: test_recentArticle (__main__.testXenagos)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/testing.py\", line 459, in test_recentArticle\n    days = (datetime.datetime.today() -  datetime.datetime.strptime(date.decode(), '%b %d, %Y')).days\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 510, in _strptime_datetime\n    tt, fraction = _strptime(data_string, format)\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 346, in _strptime\n    data_string[found.end():])\nValueError: unconverted data remains: \"\n\n----------------------------------------------------------------------\nRan 30 tests in 5.156s\n\nFAILED (errors=1)\n\n```",
        "ts": "1570017894.057500",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "\n```\n.............................E\n======================================================================\nERROR: test_recentArticle (__main__.testXenagos)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/testing.py\", line 459, in test_recentArticle\n    days = (datetime.datetime.today() -  datetime.datetime.strptime(date.decode(), '%b %d, %Y')).days\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 510, in _strptime_datetime\n    tt, fraction = _strptime(data_string, format)\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 346, in _strptime\n    data_string[found.end():])\nValueError: unconverted data remains: \"\n\n----------------------------------------------------------------------\nRan 30 tests in 5.862s\n\nFAILED (errors=1)\n\n```",
        "ts": "1570025095.000100",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "Nightly completed",
        "ts": "1570027877.000200",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-02 14:51:30,796 INFO nightly.py took 3:55:56.266452\n```",
        "ts": "1570027878.000300",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "\n```\nF............................E\n======================================================================\nERROR: test_recentArticle (__main__.testXenagos)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/testing.py\", line 459, in test_recentArticle\n    days = (datetime.datetime.today() -  datetime.datetime.strptime(date.decode(), '%b %d, %Y')).days\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 510, in _strptime_datetime\n    tt, fraction = _strptime(data_string, format)\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 346, in _strptime\n    data_string[found.end():])\nValueError: unconverted data remains: \"\n\n======================================================================\nFAIL: test_Atarka (__main__.testXenagos)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/testing.py\", line 19, in test_Atarka\n    self.assertNotEqual(-1, data[bIndex:eIndex].find('Atarka'))\nAssertionError: -1 == -1\n\n----------------------------------------------------------------------\nRan 30 tests in 35.013s\n\nFAILED (failures=1, errors=1)\n\n```",
        "ts": "1570032324.000400",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "\n```\nF............................E\n======================================================================\nERROR: test_recentArticle (__main__.testXenagos)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/testing.py\", line 459, in test_recentArticle\n    days = (datetime.datetime.today() -  datetime.datetime.strptime(date.decode(), '%b %d, %Y')).days\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 510, in _strptime_datetime\n    tt, fraction = _strptime(data_string, format)\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 346, in _strptime\n    data_string[found.end():])\nValueError: unconverted data remains: \"\n\n======================================================================\nFAIL: test_Atarka (__main__.testXenagos)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/testing.py\", line 19, in test_Atarka\n    self.assertNotEqual(-1, data[bIndex:eIndex].find('Atarka'))\nAssertionError: -1 == -1\n\n----------------------------------------------------------------------\nRan 30 tests in 3.149s\n\nFAILED (failures=1, errors=1)\n\n```",
        "ts": "1570039492.000500",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-02 18:26:53,004 INFO cards.py took 0:10:46.882467\n```",
        "ts": "1570040800.000600",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-02 18:50:17,240 CRITICAL Uncaught exception\nTraceback (most recent call last):\n  File \"&lt;string&gt;\", line 1, in &lt;module&gt;\n  File \"\/home\/ubuntu\/edhrec\/web\/nightly.py\", line 693, in make_commander\n    tribelinks=data['tribelinks']\n  File \"\/home\/ubuntu\/edhrec\/web\/web.py\", line 186, in make_page\n    repls['panels'] = make_panels(panels, card, name, repls=repls, recentdecks=recentdecks, articles=articles, tribelinks=tribelinks, partnercounts=partnercounts)\n  File \"\/home\/ubuntu\/edhrec\/web\/web.py\", line 238, in make_panels\n    outpanels['card'] = cardview.toJSON()\n  File \"\/home\/ubuntu\/edhrec\/web\/classes.py\", line 119, in toJSON\n    for i, card in enumerate(out['cards']):\nKeyError: 'cards'\n```",
        "ts": "1570042205.000700",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```[02\/Oct\/2019:18:50:36] HTTP \nTraceback (most recent call last):\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 630, in respond\n    self._do_respond(path_info)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 689, in _do_respond\n    response.body = self.handler()\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/encoding.py\", line 221, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/jsontools.py\", line 58, in json_handler\n    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cpdispatch.py\", line 54, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"\/home\/ubuntu\/edhrec\/api\/recs.py\", line 176, in index\n    card = get_shit(name, dir='cards')\n  File \"\/home\/ubuntu\/edhrec\/api\/util.py\", line 32, in get_shit\n    **CardView(cardname).toJSON()\n  File \"\/home\/ubuntu\/edhrec\/web\/classes.py\", line 119, in toJSON\n    for i, card in enumerate(out['cards']):\nKeyError: 'cards'\n```",
        "ts": "1570042224.000800",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-02 18:57:09,236 CRITICAL Uncaught exception\nTraceback (most recent call last):\n  File \"\/usr\/lib\/python3.5\/code.py\", line 91, in runcode\n    exec(code, self.locals)\n  File \"&lt;console&gt;\", line 1, in &lt;module&gt;\nAttributeError: 'list' object has no attribute 'keys'\n```",
        "ts": "1570042617.000900",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-02 18:58:23,477 CRITICAL Uncaught exception\nTraceback (most recent call last):\n  File \"&lt;string&gt;\", line 1, in &lt;module&gt;\n  File \"\/home\/ubuntu\/edhrec\/web\/nightly.py\", line 32, in &lt;module&gt;\n    from edhrec.web.classes import CardView, CardList\n  File \"\/home\/ubuntu\/edhrec\/web\/classes.py\", line 115\n    for i in len(out['image_uris']:)\n                                  ^\nSyntaxError: invalid syntax\n```",
        "ts": "1570042691.001000",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-02 18:58:36,925 CRITICAL Uncaught exception\nTraceback (most recent call last):\n  File \"&lt;string&gt;\", line 1, in &lt;module&gt;\n  File \"\/home\/ubuntu\/edhrec\/web\/nightly.py\", line 693, in make_commander\n    tribelinks=data['tribelinks']\n  File \"\/home\/ubuntu\/edhrec\/web\/web.py\", line 186, in make_page\n    repls['panels'] = make_panels(panels, card, name, repls=repls, recentdecks=recentdecks, articles=articles, tribelinks=tribelinks, partnercounts=partnercounts)\n  File \"\/home\/ubuntu\/edhrec\/web\/web.py\", line 238, in make_panels\n    outpanels['card'] = cardview.toJSON()\n  File \"\/home\/ubuntu\/edhrec\/web\/classes.py\", line 115, in toJSON\n    for i in len(out['image_uris']):\nTypeError: 'int' object is not iterable\n```",
        "ts": "1570042704.001100",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "\n```\nF............................E\n======================================================================\nERROR: test_recentArticle (__main__.testXenagos)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/testing.py\", line 459, in test_recentArticle\n    days = (datetime.datetime.today() -  datetime.datetime.strptime(date.decode(), '%b %d, %Y')).days\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 510, in _strptime_datetime\n    tt, fraction = _strptime(data_string, format)\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 346, in _strptime\n    data_string[found.end():])\nValueError: unconverted data remains: \"\n\n======================================================================\nFAIL: test_Atarka (__main__.testXenagos)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/testing.py\", line 19, in test_Atarka\n    self.assertNotEqual(-1, data[bIndex:eIndex].find('Atarka'))\nAssertionError: -1 == -1\n\n----------------------------------------------------------------------\nRan 30 tests in 2.630s\n\nFAILED (failures=1, errors=1)\n\n```",
        "ts": "1570046691.001200",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-02 20:05:12,137 INFO cards.py took 0:05:04.970721\n```",
        "ts": "1570046699.001300",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "Nightly started, onlydecks=False, skipdecks=False",
        "ts": "1570046713.001400",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-02 20:17:56,122 INFO daily.py took 0:00:24.604343\n```",
        "ts": "1570047463.001500",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-02 20:27:08,254 INFO archidekt.py took 0:22:54.734630\n```",
        "ts": "1570048016.001600",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-02 20:54:46,526 INFO deckstats.py took 0:25:37.751733\n```",
        "ts": "1570049674.001700",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-02 21:44:35,923 INFO mtggoldfish.py took 0:29:30.341870\n```",
        "ts": "1570052663.001800",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```[02\/Oct\/2019:21:46:33] HTTP \nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/core\/cards.py\", line 729, in url_to_name\n    return cache.get('cards\/urls\/' + url)\n  File \"\/home\/ubuntu\/edhrec\/core\/cache.py\", line 67, in get\n    raise NotInCache(key)\nedhrec.core.cache.NotInCache: cards\/urls\/foobar\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/api\/commanders.py\", line 103, in index\n    commander = cards.url_to_name('-'.join(cmdr_tokens[:i+1]))\n  File \"\/home\/ubuntu\/edhrec\/core\/cards.py\", line 731, in url_to_name\n    raise KeyError(e)\nKeyError: NotInCache('cards\/urls\/foobar',)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 630, in respond\n    self._do_respond(path_info)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 689, in _do_respond\n    response.body = self.handler()\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/encoding.py\", line 221, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/jsontools.py\", line 58, in json_handler\n    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cpdispatch.py\", line 54, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"\/home\/ubuntu\/edhrec\/api\/commanders.py\", line 105, in index\n    except (cache.NotInCache, KeyError):\nNameError: name 'cache' is not defined\n```",
        "ts": "1570052781.001900",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```[02\/Oct\/2019:21:48:01] HTTP \nTraceback (most recent call last):\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 630, in respond\n    self._do_respond(path_info)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 689, in _do_respond\n    response.body = self.handler()\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/encoding.py\", line 221, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/jsontools.py\", line 58, in json_handler\n    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cpdispatch.py\", line 54, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"\/home\/ubuntu\/edhrec\/api\/commanders.py\", line 127, in index\n    filtin, filtout, filters = parse_fstr(kwargs['f'])\nKeyError: 'f'\n```",
        "ts": "1570052869.002000",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```[02\/Oct\/2019:21:48:31] HTTP \nTraceback (most recent call last):\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 630, in respond\n    self._do_respond(path_info)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 689, in _do_respond\n    response.body = self.handler()\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/encoding.py\", line 221, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/jsontools.py\", line 58, in json_handler\n    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cpdispatch.py\", line 54, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"\/home\/ubuntu\/edhrec\/api\/commanders.py\", line 127, in index\n    filtin, filtout, filters = parse_fstr(kwargs['f'])\n  File \"\/home\/ubuntu\/edhrec\/api\/commanders.py\", line 158, in parse_fstr\n    f = urllib.parse.unquote(f)\nNameError: name 'urllib' is not defined\n```",
        "ts": "1570052898.002100",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```[02\/Oct\/2019:21:49:48] HTTP \nTraceback (most recent call last):\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 630, in respond\n    self._do_respond(path_info)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 689, in _do_respond\n    response.body = self.handler()\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/encoding.py\", line 221, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/jsontools.py\", line 58, in json_handler\n    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cpdispatch.py\", line 54, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"\/home\/ubuntu\/edhrec\/api\/commanders.py\", line 129, in index\n    data = origin.getcommanders(\nNameError: name 'origin' is not defined\n```",
        "ts": "1570052976.002200",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```[02\/Oct\/2019:21:50:11] HTTP \nTraceback (most recent call last):\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 630, in respond\n    self._do_respond(path_info)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 689, in _do_respond\n    response.body = self.handler()\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/encoding.py\", line 221, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/jsontools.py\", line 58, in json_handler\n    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cpdispatch.py\", line 54, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"\/home\/ubuntu\/edhrec\/api\/commanders.py\", line 140, in index\n    card = CardView(commander, label=self._commander_label(data))\nNameError: name 'CardView' is not defined\n```",
        "ts": "1570052998.002300",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```[02\/Oct\/2019:21:50:52] HTTP \nTraceback (most recent call last):\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 630, in respond\n    self._do_respond(path_info)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 689, in _do_respond\n    response.body = self.handler()\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/encoding.py\", line 221, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/jsontools.py\", line 58, in json_handler\n    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cpdispatch.py\", line 54, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"\/home\/ubuntu\/edhrec\/api\/commanders.py\", line 142, in index\n    return web.make_page('',\nNameError: name 'web' is not defined\n```",
        "ts": "1570053040.002400",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```[02\/Oct\/2019:21:51:23] HTTP \nTraceback (most recent call last):\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 630, in respond\n    self._do_respond(path_info)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 689, in _do_respond\n    response.body = self.handler()\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/encoding.py\", line 221, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/jsontools.py\", line 58, in json_handler\n    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cpdispatch.py\", line 54, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"\/home\/ubuntu\/edhrec\/api\/commanders.py\", line 151, in index\n    json_only=True)\n  File \"\/home\/ubuntu\/edhrec\/web\/web.py\", line 225, in make_page\n    return json.dump(repls2, f, cls=MyEncoder, separators=(',', ':'))\n  File \"\/usr\/lib\/python3.5\/json\/__init__.py\", line 179, in dump\n    fp.write(chunk)\nValueError: I\/O operation on closed file.\n```",
        "ts": "1570053071.002500",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "\n```\nF...........................FE\n======================================================================\nERROR: test_recentArticle (__main__.testXenagos)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/testing.py\", line 459, in test_recentArticle\n    days = (datetime.datetime.today() -  datetime.datetime.strptime(date.decode(), '%b %d, %Y')).days\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 510, in _strptime_datetime\n    tt, fraction = _strptime(data_string, format)\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 346, in _strptime\n    data_string[found.end():])\nValueError: unconverted data remains: \"\n\n======================================================================\nFAIL: test_Atarka (__main__.testXenagos)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/testing.py\", line 19, in test_Atarka\n    self.assertNotEqual(-1, data[bIndex:eIndex].find('Atarka'))\nAssertionError: -1 == -1\n\n======================================================================\nFAIL: test_random (__main__.testXenagos)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/testing.py\", line 467, in test_random\n    self.assertNotEqual(-1, data.find('Enchantment'.encode()))\nAssertionError: -1 == -1\n\n----------------------------------------------------------------------\nRan 30 tests in 2.737s\n\nFAILED (failures=2, errors=1)\n\n```",
        "ts": "1570053891.002600",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```[02\/Oct\/2019:22:25:20] HTTP \nTraceback (most recent call last):\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 630, in respond\n    self._do_respond(path_info)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 694, in _do_respond\n    response.finalize()\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 896, in finalize\n    content = self.collapse_body()\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 854, in collapse_body\n    new_body = b''.join(self.body)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cpcompat.py\", line 130, in json_encode\n    for chunk in _json_encode(value):\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/simplejson\/encoder.py\", line 696, in _iterencode\n    for chunk in _iterencode_dict(o, _current_indent_level):\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/simplejson\/encoder.py\", line 652, in _iterencode_dict\n    for chunk in chunks:\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/simplejson\/encoder.py\", line 652, in _iterencode_dict\n    for chunk in chunks:\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/simplejson\/encoder.py\", line 531, in _iterencode_list\n    for chunk in chunks:\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/simplejson\/encoder.py\", line 652, in _iterencode_dict\n    for chunk in chunks:\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/simplejson\/encoder.py\", line 652, in _iterencode_dict\n    for chunk in chunks:\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/simplejson\/encoder.py\", line 716, in _iterencode\n    o = _default(o)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/simplejson\/encoder.py\", line 273, in default\n    o.__class__.__name__)\nTypeError: Object of type date is not JSON serializable\n```",
        "ts": "1570055107.002700",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-02 22:38:09,702 INFO update_deckswithprices.py took 0:34:16.018844\nNew deck count from past 2 days: \n- Other: 0\n- deckstats: 417\n- MTGGoldfish: 493\n- Archidekt: 598\n```",
        "ts": "1570055877.002800",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-02 23:05:05,150 CRITICAL Uncaught exception\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/checks.py\", line 8, in &lt;module&gt;\n    import edhrec.core.database as database\n  File \"\/home\/ubuntu\/edhrec\/core\/database.py\", line 23, in &lt;module&gt;\n    import edhrec.core.cards as cards\n  File \"\/home\/ubuntu\/edhrec\/core\/cards.py\", line 30, in &lt;module&gt;\n    _CARDS = cache.get('allcards')\n  File \"\/home\/ubuntu\/edhrec\/core\/cache.py\", line 52, in get\n    cur.execute(query, (key.lower(),))\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/psycopg2\/extras.py\", line 141, in execute\n    return super(DictCursor, self).execute(query, vars)\npsycopg2.OperationalError: out of memory\nDETAIL:  Failed on request of size 208051159.\n\n```",
        "ts": "1570057492.002900",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "\n```\nF............................E\n======================================================================\nERROR: test_recentArticle (__main__.testXenagos)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/testing.py\", line 459, in test_recentArticle\n    days = (datetime.datetime.today() -  datetime.datetime.strptime(date.decode(), '%b %d, %Y')).days\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 510, in _strptime_datetime\n    tt, fraction = _strptime(data_string, format)\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 346, in _strptime\n    data_string[found.end():])\nValueError: unconverted data remains: \"\n\n======================================================================\nFAIL: test_Atarka (__main__.testXenagos)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/testing.py\", line 19, in test_Atarka\n    self.assertNotEqual(-1, data[bIndex:eIndex].find('Atarka'))\nAssertionError: -1 == -1\n\n----------------------------------------------------------------------\nRan 30 tests in 3.287s\n\nFAILED (failures=1, errors=1)\n\n```",
        "ts": "1570061091.003000",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-03 00:11:35,156 INFO cards.py took 0:11:26.388339\n```",
        "ts": "1570061482.003100",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "Nightly completed",
        "ts": "1570062107.003200",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-03 00:22:00,440 INFO nightly.py took 4:16:34.655886\n```",
        "ts": "1570062108.003300",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-03 00:27:55,636 CRITICAL Uncaught exception\nTraceback (most recent call last):\n  File \".\/api.py\", line 155, in &lt;module&gt;\n    class App(object):\n  File \".\/api.py\", line 158, in App\n    import deckpreview\n  File \"\/home\/ubuntu\/edhrec\/api\/deckpreview.py\", line 6, in &lt;module&gt;\n    import nightly\nImportError: No module named 'nightly'\n```",
        "ts": "1570062463.003400",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-03 00:28:46,219 CRITICAL Uncaught exception\nTraceback (most recent call last):\n  File \".\/api.py\", line 155, in &lt;module&gt;\n    class App(object):\n  File \".\/api.py\", line 158, in App\n    import deckpreview\n  File \"\/home\/ubuntu\/edhrec\/api\/deckpreview.py\", line 6, in &lt;module&gt;\n    import nightly\nImportError: No module named 'nightly'\n```",
        "ts": "1570062513.003500",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-03 00:29:02,557 CRITICAL Uncaught exception\nTraceback (most recent call last):\n  File \".\/api.py\", line 155, in &lt;module&gt;\n    class App(object):\n  File \".\/api.py\", line 158, in App\n    import deckpreview\n  File \"\/home\/ubuntu\/edhrec\/api\/deckpreview.py\", line 25, in &lt;module&gt;\n    import edhrec.nightly.nightly as nightly\nImportError: No module named 'edhrec.nightly'\n```",
        "ts": "1570062530.003600",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-03 00:29:16,459 CRITICAL Uncaught exception\nTraceback (most recent call last):\n  File \".\/api.py\", line 155, in &lt;module&gt;\n    class App(object):\n  File \".\/api.py\", line 167, in App\n    deckpreview = DeckPreview()\nNameError: name 'DeckPreview' is not defined\n```",
        "ts": "1570062544.003700",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-03 00:38:02,535 INFO archidekt.py took 0:23:51.931944\n```",
        "ts": "1570063070.003800",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-03 01:05:25,389 INFO deckstats.py took 0:25:21.974122\n```",
        "ts": "1570064713.003900",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-03 01:05:57,838 CRITICAL Uncaught exception\nTraceback (most recent call last):\n  File \"\/usr\/lib\/python3.5\/code.py\", line 91, in runcode\n    exec(code, self.locals)\n  File \"&lt;console&gt;\", line 1, in &lt;module&gt;\nAttributeError: module 'json' has no attribute 'dujson'\n```",
        "ts": "1570064745.004000",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```[03\/Oct\/2019:01:53:11] HTTP \nTraceback (most recent call last):\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 630, in respond\n    self._do_respond(path_info)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 689, in _do_respond\n    response.body = self.handler()\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/encoding.py\", line 221, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/jsontools.py\", line 58, in json_handler\n    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cpdispatch.py\", line 54, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"\/home\/ubuntu\/edhrec\/web\/dynamic.py\", line 197, in recjson\n    card_scn = cards.scn(cardname)\n  File \"\/home\/ubuntu\/edhrec\/core\/cards.py\", line 714, in scn\n    out = get(cardname)['name']\n  File \"\/home\/ubuntu\/edhrec\/core\/cards.py\", line 518, in get\n    name = sanitize_url(name.split('(')[0].strip())\nAttributeError: 'list' object has no attribute 'split'\n```",
        "ts": "1570067579.004100",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```[03\/Oct\/2019:01:53:58] HTTP \nTraceback (most recent call last):\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 630, in respond\n    self._do_respond(path_info)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 689, in _do_respond\n    response.body = self.handler()\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/encoding.py\", line 221, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/jsontools.py\", line 58, in json_handler\n    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cpdispatch.py\", line 54, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"\/home\/ubuntu\/edhrec\/web\/dynamic.py\", line 197, in recjson\n    card_scn = cards.scn(cardname)\n  File \"\/home\/ubuntu\/edhrec\/core\/cards.py\", line 714, in scn\n    out = get(cardname)['name']\n  File \"\/home\/ubuntu\/edhrec\/core\/cards.py\", line 518, in get\n    name = sanitize_url(name.split('(')[0].strip())\nAttributeError: 'list' object has no attribute 'split'\n```",
        "ts": "1570067625.004200",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-03 01:54:18,699 INFO mtggoldfish.py took 0:28:34.478092\n```",
        "ts": "1570067646.004300",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "\n```\nF............................E\n======================================================================\nERROR: test_recentArticle (__main__.testXenagos)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/testing.py\", line 459, in test_recentArticle\n    days = (datetime.datetime.today() -  datetime.datetime.strptime(date.decode(), '%b %d, %Y')).days\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 510, in _strptime_datetime\n    tt, fraction = _strptime(data_string, format)\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 346, in _strptime\n    data_string[found.end():])\nValueError: unconverted data remains: \"\n\n======================================================================\nFAIL: test_Atarka (__main__.testXenagos)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/testing.py\", line 19, in test_Atarka\n    self.assertNotEqual(-1, data[bIndex:eIndex].find('Atarka'))\nAssertionError: -1 == -1\n\n----------------------------------------------------------------------\nRan 30 tests in 42.598s\n\nFAILED (failures=1, errors=1)\n\n```",
        "ts": "1570068331.004400",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-03 02:43:09,056 INFO update_deckswithprices.py took 0:31:45.412424\nNew deck count from past 2 days: \n- deckstats: 256\n- MTGGoldfish: 301\n- Other: 0\n- Archidekt: 578\n```",
        "ts": "1570070576.004500",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "Nightly started, onlydecks=False, skipdecks=False",
        "ts": "1570070587.004600",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```[03\/Oct\/2019:03:22:08] HTTP \nTraceback (most recent call last):\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 630, in respond\n    self._do_respond(path_info)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 689, in _do_respond\n    response.body = self.handler()\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/encoding.py\", line 221, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/jsontools.py\", line 58, in json_handler\n    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cpdispatch.py\", line 54, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"\/home\/ubuntu\/edhrec\/api\/recs.py\", line 163, in index\n    data = self.validate_deck(cherrypy.request.json)\n  File \"\/home\/ubuntu\/edhrec\/api\/recs.py\", line 89, in validate_deck\n    if parsed_name in data['commanders']:\nKeyError: 'commanders'\n```",
        "ts": "1570072916.004700",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```[03\/Oct\/2019:03:22:59] HTTP \nTraceback (most recent call last):\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 630, in respond\n    self._do_respond(path_info)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cprequest.py\", line 689, in _do_respond\n    response.body = self.handler()\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/encoding.py\", line 221, in __call__\n    self.body = self.oldhandler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/lib\/jsontools.py\", line 58, in json_handler\n    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)\n  File \"\/usr\/local\/lib\/python3.5\/dist-packages\/cherrypy\/_cpdispatch.py\", line 54, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File \"\/home\/ubuntu\/edhrec\/api\/recs.py\", line 163, in index\n    data = self.validate_deck(cherrypy.request.json)\n  File \"\/home\/ubuntu\/edhrec\/api\/recs.py\", line 89, in validate_deck\n    if parsed_name in data['commanders']:\nKeyError: 'commanders'\n```",
        "ts": "1570072967.004800",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "\n```\nF............................E\n======================================================================\nERROR: test_recentArticle (__main__.testXenagos)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/testing.py\", line 459, in test_recentArticle\n    days = (datetime.datetime.today() -  datetime.datetime.strptime(date.decode(), '%b %d, %Y')).days\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 510, in _strptime_datetime\n    tt, fraction = _strptime(data_string, format)\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 346, in _strptime\n    data_string[found.end():])\nValueError: unconverted data remains: \"\n\n======================================================================\nFAIL: test_Atarka (__main__.testXenagos)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/testing.py\", line 19, in test_Atarka\n    self.assertNotEqual(-1, data[bIndex:eIndex].find('Atarka'))\nAssertionError: -1 == -1\n\n----------------------------------------------------------------------\nRan 30 tests in 1.388s\n\nFAILED (failures=1, errors=1)\n\n```",
        "ts": "1570075490.004900",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "\n```\nF............................E\n======================================================================\nERROR: test_recentArticle (__main__.testXenagos)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/testing.py\", line 459, in test_recentArticle\n    days = (datetime.datetime.today() -  datetime.datetime.strptime(date.decode(), '%b %d, %Y')).days\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 510, in _strptime_datetime\n    tt, fraction = _strptime(data_string, format)\n  File \"\/usr\/lib\/python3.5\/_strptime.py\", line 346, in _strptime\n    data_string[found.end():])\nValueError: unconverted data remains: \"\n\n======================================================================\nFAIL: test_Atarka (__main__.testXenagos)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"\/home\/ubuntu\/edhrec\/batch\/testing.py\", line 19, in test_Atarka\n    self.assertNotEqual(-1, data[bIndex:eIndex].find('Atarka'))\nAssertionError: -1 == -1\n\n----------------------------------------------------------------------\nRan 30 tests in 33.538s\n\nFAILED (failures=1, errors=1)\n\n```",
        "ts": "1570082722.005000",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "Nightly completed",
        "ts": "1570084813.005100",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    },
    {
        "type": "message",
        "subtype": "bot_message",
        "text": "```2019-10-03 06:40:26,655 INFO nightly.py took 3:57:07.797770\n```",
        "ts": "1570084814.005200",
        "username": "edhrecbot",
        "icons": {
            "emoji": ":robot_face:",
            "image_64": "https:\/\/a.slack-edge.com\/80588\/img\/emoji_2017_12_06\/apple\/1f916.png"
        },
        "bot_id": "B2867AJ5C"
    }
]